version: "3.1"

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    #   - MYSQL_DATABASE=radio
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      #   - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    links:
      - db
# services:
#   db:
#     image: mariadb:10.3
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#     # ports:
#     #   - "3306:3306"

#   phpmyadmin:
#     image: phpmyadmin
#     restart: always
#     ports:
#       - "8080:80"
#     # environment:
#     #   - PMA_ARBITRARY=1
